# Git
# ===
alias g='git'
alias ga='git add '
alias gap='git add -p'
alias gb='git branch'
alias gc='git commit'
alias gcm='git commit -m '
alias gd='git diff'
alias gdc='git diff --cached'
alias gdw='git diff --word-diff'
alias gl='git l'
alias gla='git la'
alias gpush='git push'
alias gs='git status -sb'
alias gshow='git show'

# Postgresql
# ==========
alias pgusers='psql template1 -c "\du"'

# Bundler
# =======
alias be='echo "WARNING: Use binstubs instead of bundle exec"; bundle exec'
alias brake='be rake'

# vim
# ===
alias m='mvim' #-c "au VimLeave * !open -a Terminal"'
alias v='vim'

export EDITOR='mvim -f'
export BUNDLER_EDITOR=mvim

# Foreman
# =======

# If a Procfile.local file exists, use it. Otherwise run foreman normally
alias f='[ -e Procfile.local ] && foreman start -f Procfile.local || foreman start'

# Terminal
# ========

# Colorize the terminal
export CLICOLOR=1
export LSCOLORS=Exfxcxdxbxegedabagacad
export GREP_OPTIONS='--color=auto'

# Initialize colors.
autoload -U colors
colors

# Allow for functions in the prompt.
setopt PROMPT_SUBST

# Set the prompt to be of the format:
# ~/<path>@<git-branch>
parse_git_branch() {
  branch="$(git symbolic-ref HEAD 2>/dev/null)" || return
  echo "@${branch#refs/heads/}"
}
PROMPT=$'%{${fg[cyan]}%}%B%~%b%{${fg[yellow]}%}$(parse_git_branch)%{${fg[default]}%} '

autoload -U compinit
compinit

ulimit -n 10000

# Load from /usr/local/bin before /usr/bin
export PATH=/usr/local/bin:$PATH

# Ruby
# ====

# rbenv
if which rbenv > /dev/null; then eval "$(rbenv init - --no-rehash)"; fi

# Binstubs
export PATH="./bin:$PATH"

# C Flags
# =======
export CFLAGS="-arch x86_64"
export ARCHFLAGS="-arch x86_64"

# Java
# ====
export JAVA_HOME=$(/usr/libexec/java_home -v 1.7)

# OSX Terminal
# ============

# Set Apple Terminal.app resume directory
if [[ $TERM_PROGRAM == "Apple_Terminal" ]] {
  function chpwd {
    local SEARCH=' '
    local REPLACE='%20'
    local PWD_URL="file://$HOSTNAME${PWD//$SEARCH/$REPLACE}"
    printf '\e]7;%s\a' $PWD_URL
  }

  chpwd
}
