# Git
# ===
git config --global core.autocrlf input

alias g='git'
alias ga='git add '
alias gap='git add -p'
alias gb='git branch'
alias gc='git commit'
alias gcm='git commit -m '
alias gd='git diff'
alias gdc='git diff --cached'
alias gdw='git diff --word-diff'
alias gl='git l'
alias gla='git la'
alias gpush='git push'
alias gs='git status -sb'
alias gshow='git show'

# Postgresql
# ==========
alias pgusers='psql template1 -c "\du"'

# Bundler
# =======
alias be='echo "WARNING: Use binstubs instead of bundle exec"; bundle exec'
alias brake='be rake'

# vim
# ===
alias m='mvim -c "au VimLeave * !open -a Terminal"'
alias v='vim'

export EDITOR='mvim -f'
export BUNDLER_EDITOR=mvim


# Terminal
# ========

# Colorize the terminal
export CLICOLOR=1
export LSCOLORS=Exfxcxdxbxegedabagacad
export GREP_OPTIONS='--color=auto'

# Initialize colors.
autoload -U colors
colors

# Allow for functions in the prompt.
setopt PROMPT_SUBST

# Set the prompt to be of the format:
# ~/<path>@<git-branch>
parse_git_branch() {
  branch="$(git symbolic-ref HEAD 2>/dev/null)" || return
  echo "@${branch#refs/heads/}"
}
PROMPT=$'%{${fg[cyan]}%}%B%~%b%{${fg[yellow]}%}$(parse_git_branch)%{${fg[default]}%} '

autoload -U compinit
compinit

ulimit -n 10000

# Load from /usr/local/bin before /usr/bin
export PATH=/usr/local/bin:$PATH

# Ruby
# ====

# Ruby 1.9.3 + Rails improvements (https://gist.github.com/1688857)
export RUBY_GC_MALLOC_LIMIT=60000000
export RUBY_FREE_MIN=200000

# rbenv
if which rbenv > /dev/null; then eval "$(rbenv init - --no-rehash)"; fi

# Binstubs
export PATH="./bin:$PATH"

# OSX Terminal
# ============

# Set Apple Terminal.app resume directory
if [[ $TERM_PROGRAM == "Apple_Terminal" ]] {
  function chpwd {
    local SEARCH=' '
    local REPLACE='%20'
    local PWD_URL="file://$HOSTNAME${PWD//$SEARCH/$REPLACE}"
    printf '\e]7;%s\a' $PWD_URL
  }

  chpwd
}
