#!/usr/bin/env bash

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES=$BASE_DIR/dotfiles

for f in $DOTFILES/*
do
  ln -sf $f ~/.$(basename $f)
done

# bin files
# =========
ln -s $BASE_DIR/bin/* /usr/local/bin/

# vim Plugins
# ===========

rm -rf $DOTFILES/vim
mkdir $DOTFILES/vim

rm -rf $DOTFILES/.plugins
mkdir -p $DOTFILES/.plugins
cd $DOTFILES/.plugins

VIM_PLUGINS=(
  'mileszs/ack.vim'
  'gregsexton/gitv'
  'ddollar/nerdcommenter'
  'scrooloose/nerdtree'
  'tpope/vim-bundler'
  'kchmck/vim-coffee-script'
  'tpope/vim-endwise'
  'tpope/vim-fugitive'
  'tpope/vim-git'
  'tpope/vim-haml'
  'tpope/vim-markdown'
  'tpope/vim-pathogen'
  'tpope/vim-rails'
  'tpope/vim-rake'
  'tpope/vim-repeat'
  'vim-ruby/vim-ruby'
  'tpope/vim-surround'
  'venables/vim-vroom'
  'pangloss/vim-javascript'
  'briancollins/vim-jst'
)
#'Valloric/YouCompleteMe'
#'scrooloose/syntastic' -- too slow for sass
for repo in "${VIM_PLUGINS[@]}"
do
  git clone git://github.com/$repo.git $DOTFILES/.plugins/$(basename "$repo")
done

# vim-powerline
git clone -b develop git://github.com/Lokaltog/vim-powerline.git $DOTFILES/.plugins/vim-powerline

ln -s $DOTFILES/.plugins $DOTFILES/vim/bundle

# Themes
# ======

# Install Tomorrow-Theme
rm -rf $DOTFILES/.themes
mkdir -p $DOTFILES/.themes
git clone git://github.com/chriskempson/tomorrow-theme.git $DOTFILES/.themes/tomorrow-theme
ln -s $DOTFILES/.themes/tomorrow-theme/vim/colors $DOTFILES/vim/
