#!/usr/bin/env bash

# copy dotfiles
# =============


BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_DIR=$BASE_DIR/dotfiles
for f in agignore gemrc gitconfig gitignore irbrc pryrc vimrc zshrc zsh-plugins
do
  ln -sf $DOTFILES_DIR/$f ~/.$f
done

# bin files
# =========
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ln -s $BASE_DIR/bin/* /usr/local/bin/

# Make ~/.git-templates
mkdir -p ~/.git-templates/
cp -R ./dotfiles/git-templates/ ~/.git-templates/

# Build ~/.vim directory
rm -rf ~/.vim
mkdir -p ~/.vim/bundle
git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle

echo ""
echo ""
echo "Open vim and run :BundleInstall"
