#!/bin/sh

# Copy last commit hash to clipboard on commit
git log -1 --format=format:%h | pbcopy

# Take a photo
function take_and_upload_photo {
  PHOTODIR=~/.git-photos
  FILENAME=$PHOTODIR/$(date +%s).jpg
  mkdir -p $PHOTODIR
  imagesnap -q -w 3 $FILENAME

  SHA=$(git log -1 --format=format:%h)
  APIKEY=$(cat $/.dotfiles/dotfiles/.git-photos-api-key)
  curl -i -F access_token=$APIKEY -F sha=$SHA -F photo=@$FILENAME https://git-photos-dev.herokuapp.com/api/uploads
}

take_and_upload_photo >& /dev/null &
