#!/bin/sh

# Copy last commit hash to clipboard on commit
git log -1 --format=format:%h | pbcopy

# Take a photo
PHOTODIR=~/.git-photos
mkdir -p $PHOTODIR
nohup imagesnap -q -w 3 $PHOTODIR/$(date +%s).jpg &>/dev/null &
